name: "Build"

on:
  push:
    paths:
      - 'src/**'

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          az bicep build \
            --file ./src/main.bicep \
            --stdout
