name: "Test"

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Validate
        run: |
          az deployment sub what-if \
            --name "GitHub.Actions" \
            --location "uksouth" \
            --template-file ./src/main.bicep \
            --parameters @./src/main.bicepparam
